disallowed-types = [
  { path = "std::path::PathBuf", reason = "Use `use icp_project::prelude::PathBuf;` or `use icp_project::prelude::*;` instead" },
  { path = "std::path::Path", reason = "Use `icp_project::prelude::Path;` or `use icp_project::prelude::*;` instead" },
]
too-many-arguments-threshold = 12
