const ESLINT_DISABLE_COMMENT = "/* eslint-disable */";
const TS_NOCHECK_COMMENT = "// @ts-nocheck";
const DISCLAIMER_COMMENT = `// This file was automatically generated by @icp-sdk/bindgen-plugin.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.`;

export function prepareBinding(binding: string): string {
  return `${ESLINT_DISABLE_COMMENT}

${TS_NOCHECK_COMMENT}

${DISCLAIMER_COMMENT}

${binding}`;
}
