/* eslint-disable */

// This file was automatically generated by @icp-sdk/bindgen@0.1.0-beta.4.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

interface CanisterEnv {
  readonly ["ICP_CANISTER_ID:backend"]: string;
}