#![allow(dead_code)]

use std::process::Command;

use httptest::{Expectation, Server, matchers::*, responders::*};

pub(crate) mod clients;
mod context;
pub(crate) mod softhsm;

pub(crate) use context::TestContext;
use send_ctrlc::{InterruptibleChild, InterruptibleCommand};

#[cfg(unix)]
pub(crate) const PATH_SEPARATOR: &str = ":";

#[cfg(windows)]
pub(crate) const PATH_SEPARATOR: &str = ";";

// NETWORK_RANDOM_PORT, NETWORK_DOCKER, NETWORK_DOCKER_ENGINE are generated by build.rs
// with the version from network-launcher-version injected.
include!(concat!(env!("OUT_DIR"), "/network_constants.rs"));

/// An environment manifest utilizing the above network
pub(crate) const ENVIRONMENT_RANDOM_PORT: &str = r#"
environments:
  - name: random-environment
    network: random-network
"#;

pub(crate) const ENVIRONMENT_DOCKER: &str = r#"
environments:
  - name: docker-environment
    network: docker-network
"#;

pub(crate) const ENVIRONMENT_DOCKER_ENGINE: &str = r#"
environments:
  - name: docker-engine-environment
    network: docker-engine-network
"#;

/// Compiles the canister and plugin from `examples/icp-sync-plugin/` and returns
/// (canister_wasm_path, plugin_wasm_path). Cargo caches the build so subsequent
/// test runs are fast when sources haven't changed.
pub(crate) fn build_sync_plugin_example() -> (camino::Utf8PathBuf, camino::Utf8PathBuf) {
    let example_dir = camino::Utf8PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples/icp-sync-plugin");
    // Use CARGO env var when available (set by cargo test), fall back to PATH lookup.
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());

    let status = Command::new(&cargo)
        .args([
            "build",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
            "-p",
            "canister",
        ])
        .current_dir(&example_dir)
        .status()
        .expect("failed to spawn cargo build for canister");
    assert!(
        status.success(),
        "cargo build --target wasm32-unknown-unknown failed"
    );

    let status = Command::new(&cargo)
        .args([
            "build",
            "--target",
            "wasm32-wasip2",
            "--release",
            "-p",
            "plugin",
        ])
        .current_dir(&example_dir)
        .status()
        .expect("failed to spawn cargo build for plugin");

    assert!(
        status.success(),
        "cargo build --target wasm32-wasip2 failed"
    );

    (
        example_dir.join("target/wasm32-unknown-unknown/release/canister.wasm"),
        example_dir.join("target/wasm32-wasip2/release/plugin.wasm"),
    )
}

// Spawns a test server that expects a single request and responds with a 200 status code and the given body
pub(crate) fn spawn_test_server(method: &str, path: &str, body: &[u8]) -> httptest::Server {
    // Run the server
    let server = Server::run();

    // Set up the expectation
    server.expect(
        Expectation::matching(request::method_path(method.to_owned(), path.to_owned()))
            .times(1)
            .respond_with(status_code(200).body(body.to_owned())),
    );

    // Return the server instance
    server
}

// A network start by icp-cli for a test. These fields are read from the network descriptor
// after starting the network.
pub(crate) struct TestNetwork {
    pub(crate) gateway_port: u16,
    pub(crate) pocketic_config_port: Option<u16>,
    pub(crate) pocketic_instance_id: Option<usize>,
    pub(crate) root_key: Vec<u8>,
}

pub(crate) struct ChildGuard {
    child: InterruptibleChild,
}

impl ChildGuard {
    pub(crate) fn spawn(cmd: &mut Command) -> std::io::Result<Self> {
        #[cfg(unix)]
        {
            use std::os::unix::process::CommandExt;
            cmd.process_group(0);
        }
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            cmd.creation_flags(0x00000200); // CREATE_NEW_PROCESS_GROUP
        }
        let child = cmd.spawn_interruptible()?;
        Ok(Self { child })
    }

    fn send_sigint_to_process_group(&mut self) {
        #[cfg(unix)]
        {
            use nix::sys::signal::{Signal, killpg};
            use nix::unistd::Pid;

            let pid = self.child.id();
            let pgid = Pid::from_raw(pid as i32); // Child PID = PGID
            let _ = killpg(pgid, Signal::SIGINT);
            // Give the process some time to shut down gracefully
            std::thread::sleep(std::time::Duration::from_secs(2));
        }
        #[cfg(windows)]
        {
            use send_ctrlc::Interruptible;
            _ = self.child.terminate(); // CTRL_BREAK_EVENT, required to target process group
            // Give the process some time to shut down gracefully
            std::thread::sleep(std::time::Duration::from_secs(2));
        }
    }
}

impl Drop for ChildGuard {
    fn drop(&mut self) {
        match self.child.try_wait() {
            Ok(Some(_)) => {
                // Already exited, nothing to do
            }
            Ok(None) => {
                self.send_sigint_to_process_group();
                if let Err(e) = self.child.kill() {
                    eprintln!("Failed to kill child process: {e}");
                }
                if let Err(e) = self.child.wait() {
                    eprintln!("Failed to wait on child process: {e}");
                }
            }
            Err(e) => {
                eprintln!("Failed to check child process status: {e}");
            }
        }
    }
}
